package zoneFileParser

import (
	"bufio"
	"bytes"
	"fmt"
	"strings"
)

//NewWordScanner returns a WordScanner
func NewWordScanner(data []byte) *WordScanner {
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Split(bufio.ScanWords)
	return &WordScanner{data: data, scanner: scanner, wordsRead: 0}
}

//WordScanner uses bufio.Scanner to scan words of the input. Additionally it keeps track of the line (of the input) on which the scanner currently is
type WordScanner struct {
	data      []byte
	scanner   *bufio.Scanner
	wordsRead int
}

//Scan moves the Scanner to the next Token, which will then be available through the Bytes or Text method.
//False is returned when the scan stops, either by reaching the end of the input or an error.
func (ws *WordScanner) Scan() bool {
	ws.wordsRead++
	return ws.scanner.Scan()
}

//Text returns the value of the current Token generated by a call to Scan as a newly allocated string.
func (ws *WordScanner) Text() string {
	return ws.scanner.Text()
}

func (ws *WordScanner) TextLine() string {
	return fmt.Sprintf("%s at line %d", ws.Text(), ws.LineNumber())
}

//LineNumber returns the number of the line of the input data on which the current Token of the scanner is.
func (ws *WordScanner) LineNumber() int {
	lineScanner := bufio.NewScanner(bytes.NewReader(ws.data))
	i := 0
	lineNr := 1
	for lineScanner.Scan() && i < ws.wordsRead {
		scanner := bufio.NewScanner(strings.NewReader(lineScanner.Text()))
		scanner.Split(bufio.ScanWords)
		for scanner.Scan() {
			i++
			if i == ws.wordsRead {
				return lineNr
			}
		}
		lineNr++
	}
	return lineNr
}
