// Code generated by "stringer -type=Type"; DO NOT EDIT.

package connection

import "strconv"

const _Type_name = "TCPSCION"

var _Type_index = [...]uint8{0, 3, 8}

func (i Type) String() string {
	i -= 1
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
