// Code generated by "stringer -type=KeySpaceID"; DO NOT EDIT.

package keys

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RainsKeySpace-0]
}

const _KeySpaceID_name = "RainsKeySpace"

var _KeySpaceID_index = [...]uint8{0, 13}

func (i KeySpaceID) String() string {
	if i < 0 || i >= KeySpaceID(len(_KeySpaceID_index)-1) {
		return "KeySpaceID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeySpaceID_name[_KeySpaceID_index[i]:_KeySpaceID_index[i+1]]
}
