// Code generated by "stringer -type=CertificateUsage"; DO NOT EDIT.

package object

import "strconv"

const _CertificateUsage_name = "CUTrustAnchorCUEndEntity"

var _CertificateUsage_index = [...]uint8{0, 13, 24}

func (i CertificateUsage) String() string {
	i -= 2
	if i < 0 || i >= CertificateUsage(len(_CertificateUsage_index)-1) {
		return "CertificateUsage(" + strconv.FormatInt(int64(i+2), 10) + ")"
	}
	return _CertificateUsage_name[_CertificateUsage_index[i]:_CertificateUsage_index[i+1]]
}
