// Code generated by "stringer -type=Type"; DO NOT EDIT.

package object

import "strconv"

const _Type_name = "OTNameOTIP6AddrOTIP4AddrOTRedirectionOTDelegationOTNamesetOTCertInfoOTServiceInfoOTRegistrarOTRegistrantOTInfraKeyOTExtraKeyOTNextKeyOTScionAddr6OTScionAddr4"

var _Type_index = [...]uint8{0, 6, 15, 24, 37, 49, 58, 68, 81, 92, 104, 114, 124, 133, 145, 157}

func (i Type) String() string {
	i -= 1
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
