// Code generated by goyacc -p ZFP zonefileParser.y. DO NOT EDIT.

//line zonefileParser.y:8
package zonefile

import __yyfmt__ "fmt"

//line zonefileParser.y:9
import (
	"bufio"
	"bytes"
	"encoding/hex"
	"errors"
	"fmt"
	log "github.com/inconshreveable/log15"
	"github.com/netsec-ethz/rains/internal/pkg/algorithmTypes"
	"github.com/netsec-ethz/rains/internal/pkg/datastructures/bitarray"
	"github.com/netsec-ethz/rains/internal/pkg/keys"
	"github.com/netsec-ethz/rains/internal/pkg/object"
	"github.com/netsec-ethz/rains/internal/pkg/section"
	"github.com/netsec-ethz/rains/internal/pkg/signature"
	
	"github.com/scionproto/scion/go/lib/snet"
	"golang.org/x/crypto/ed25519"
	"io/ioutil"
	"net"
	"strconv"
	"strings"
)

//AddSigs adds signatures to section
func AddSigs(sec section.WithSigForward, signatures []signature.Sig) {
	for _, sig := range signatures {
		sec.AddSig(sig)
	}
}

func DecodePublicKeyID(keyphase string) (keys.PublicKeyID, error) {
	phase, err := strconv.Atoi(keyphase)
	if err != nil {
		return keys.PublicKeyID{}, errors.New("keyphase is not a number")
	}
	return keys.PublicKeyID{
		Algorithm: algorithmTypes.Ed25519,
		KeyPhase:  phase,
		KeySpace:  keys.RainsKeySpace,
	}, nil
}

// DecodeEd25519PublicKeyData returns the publicKey or an error in case
// pkeyInput is malformed i.e. it is not in zone file format.
func DecodeEd25519PublicKeyData(pkeyInput string, keyphase string) (keys.PublicKey, error) {
	publicKeyID, err := DecodePublicKeyID(keyphase)
	if err != nil {
		return keys.PublicKey{}, err
	}
	pKey, err := hex.DecodeString(pkeyInput)
	if err != nil {
		return keys.PublicKey{}, err
	}
	if len(pKey) == 32 {
		publicKey := keys.PublicKey{Key: ed25519.PublicKey(pKey), PublicKeyID: publicKeyID}
		return publicKey, nil
	}
	return keys.PublicKey{}, fmt.Errorf("wrong public key length: got %d, want: 32", len(pKey))
}

func DecodeCertificate(ptype object.ProtocolType, usage object.CertificateUsage,
	hashAlgo algorithmTypes.Hash, certificat string) (object.Certificate,
	error) {
	data, err := hex.DecodeString(certificat)
	if err != nil {
		return object.Certificate{}, err
	}
	return object.Certificate{
		Type:     ptype,
		Usage:    usage,
		HashAlgo: hashAlgo,
		Data:     data,
	}, nil
}

func DecodeCT(ctproof string) (object.CTProof, error) {
	data, err := hex.DecodeString(ctproof)
	if err != nil {
		return object.CTProof{}, err
	}
	return object.CTProof{
		Data: data,
	}, nil
}

func DecodeSrv(name, portString, priorityString string) (object.ServiceInfo, error) {
	port, err := strconv.Atoi(portString)
	if err != nil || port < 0 || port > 65535 {
		return object.ServiceInfo{}, errors.New("Port is not a number or out of range")
	}
	priority, err := strconv.Atoi(priorityString)
	if err != nil || port < 0 {
		return object.ServiceInfo{}, errors.New("Priority is not a number or negative")
	}
	return object.ServiceInfo{
		Name:     name,
		Port:     uint16(port),
		Priority: uint(priority),
	}, nil
}

func DecodeValidity(validSince, validUntil string) (int64, int64, error) {
	vsince, err := strconv.ParseInt(validSince, 10, 64)
	if err != nil || vsince < 0 {
		return 0, 0, errors.New("validSince is not a number or negative")
	}
	vuntil, err := strconv.ParseInt(validUntil, 10, 64)
	if err != nil || vuntil < 0 {
		return 0, 0, errors.New("validUntil is not a number or negative")
	}
	return vsince, vuntil, nil
}

//Result gets stored in this variable
var output []section.WithSigForward

//line zonefileParser.y:131
type ZFPSymType struct {
	yys          int
	str          string
	assertion    *section.Assertion
	assertions   []*section.Assertion
	shard        *section.Shard
	pshard       *section.Pshard
	zone         *section.Zone
	sections     []section.WithSigForward
	objects      []object.Object
	object       object.Object
	objectTypes  []object.Type
	objectType   object.Type
	signatures   []signature.Sig
	signature    signature.Sig
	shardRange   []string
	publicKey    keys.PublicKey
	protocolType object.ProtocolType
	certUsage    object.CertificateUsage
	hashType     algorithmTypes.Hash
	bfAlgo       section.BloomFilterAlgo
}

const ID = 57346
const assertionType = 57347
const shardType = 57348
const pshardType = 57349
const zoneType = 57350
const nameType = 57351
const ip4Type = 57352
const ip6Type = 57353
const scionip4Type = 57354
const scionip6Type = 57355
const redirType = 57356
const delegType = 57357
const namesetType = 57358
const certType = 57359
const ctType = 57360
const srvType = 57361
const regrType = 57362
const regtType = 57363
const infraType = 57364
const extraType = 57365
const nextType = 57366
const sigType = 57367
const ed25519Type = 57368
const unspecified = 57369
const tls = 57370
const trustAnchor = 57371
const endEntity = 57372
const noHash = 57373
const sha256 = 57374
const sha384 = 57375
const sha512 = 57376
const shake256 = 57377
const fnv64 = 57378
const fnv128 = 57379
const bloomKM12 = 57380
const bloomKM16 = 57381
const bloomKM20 = 57382
const bloomKM24 = 57383
const rains = 57384
const rangeBegin = 57385
const rangeEnd = 57386
const lBracket = 57387
const rBracket = 57388
const lParenthesis = 57389
const rParenthesis = 57390

var ZFPToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ID",
	"assertionType",
	"shardType",
	"pshardType",
	"zoneType",
	"nameType",
	"ip4Type",
	"ip6Type",
	"scionip4Type",
	"scionip6Type",
	"redirType",
	"delegType",
	"namesetType",
	"certType",
	"ctType",
	"srvType",
	"regrType",
	"regtType",
	"infraType",
	"extraType",
	"nextType",
	"sigType",
	"ed25519Type",
	"unspecified",
	"tls",
	"trustAnchor",
	"endEntity",
	"noHash",
	"sha256",
	"sha384",
	"sha512",
	"shake256",
	"fnv64",
	"fnv128",
	"bloomKM12",
	"bloomKM16",
	"bloomKM20",
	"bloomKM24",
	"rains",
	"rangeBegin",
	"rangeEnd",
	"lBracket",
	"rBracket",
	"lParenthesis",
	"rParenthesis",
}
var ZFPStatenames = [...]string{}

const ZFPEofCode = 1
const ZFPErrCode = 2
const ZFPInitialStackSize = 16

//line zonefileParser.y:746

/*  Lexer  */

// The parser expects the lexer to return 0 on EOF.
const eof = 0

type ZFPLex struct {
	lines   [][]string
	lineNr  int
	linePos int
}

func (l *ZFPLex) Lex(lval *ZFPSymType) int {
	if l.lineNr == len(l.lines) {
		return eof
	}
	//read data and skip empty lines
	line := l.lines[l.lineNr]
	for len(line) == 0 {
		l.lineNr++
		if l.lineNr == len(l.lines) {
			return eof
		}
		line = l.lines[l.lineNr]
	}
	word := line[l.linePos]
	//update state
	if l.linePos == len(line)-1 {
		l.lineNr++
		l.linePos = 0
	} else {
		l.linePos++
	}
	//return token
	switch word {
	case TypeAssertion:
		return assertionType
	case TypeShard:
		return shardType
	case TypePshard:
		return pshardType
	case TypeZone:
		return zoneType
	case TypeName:
		return nameType
	case TypeIP6:
		return ip6Type
	case TypeIP4:
		return ip4Type
	case TypeScionIP6:
		return scionip6Type
	case TypeScionIP4:
		return scionip4Type
	case TypeRedirection:
		return redirType
	case TypeDelegation:
		return delegType
	case TypeNameSet:
		return namesetType
	case TypeCertificate:
		return certType
	case TypeCT:
		return ctType
	case TypeServiceInfo:
		return srvType
	case TypeRegistrar:
		return regrType
	case TypeRegistrant:
		return regtType
	case TypeInfraKey:
		return infraType
	case TypeExternalKey:
		return extraType
	case TypeNextKey:
		return nextType
	case TypeSignature:
		return sigType
	case TypeEd25519:
		return ed25519Type
	case TypeUnspecified:
		return unspecified
	case TypePTTLS:
		return tls
	case TypeCUTrustAnchor:
		return trustAnchor
	case TypeCUEndEntity:
		return endEntity
	case TypeNoHash:
		return noHash
	case TypeSha256:
		return sha256
	case TypeSha384:
		return sha384
	case TypeSha512:
		return sha512
	case TypeShake256:
		return shake256
	case TypeFnv64:
		return fnv64
	case TypeFnv128:
		return fnv128
	case TypeKM12:
		return bloomKM12
	case TypeKM16:
		return bloomKM16
	case TypeKM20:
		return bloomKM20
	case TypeKM24:
		return bloomKM24
	case TypeKSRains:
		return rains
	case "<":
		return rangeBegin
	case ">":
		return rangeEnd
	case "[":
		return lBracket
	case "]":
		return rBracket
	case "(":
		return lParenthesis
	case ")":
		return rParenthesis
	default:
		lval.str = word
		return ID
	}
}

// The parser calls this method on a parse error.
func (l *ZFPLex) Error(s string) {
	for l.linePos == 0 && l.lineNr > 0 {
		l.lineNr--
		l.linePos = len(l.lines[l.lineNr])
	}
	if l.linePos == 0 && l.lineNr == 0 {
		log.Error("syntax error:", "lineNr", 1, "wordNr", 0,
			"token", "noToken")
	} else {
		log.Error("syntax error:", "lineNr", l.lineNr+1, "wordNr", l.linePos,
			"token", l.lines[l.lineNr][l.linePos-1])
	}
}

func main() {
	file, err := ioutil.ReadFile("zonefile.txt")
	if err != nil {
		log.Error(err.Error())
		return
	}
	lines := removeComments(bufio.NewScanner(bytes.NewReader(file)))
	log.Debug("Preprocessed input", "data", lines)
	ZFPParse(&ZFPLex{lines: lines})
}

func removeComments(scanner *bufio.Scanner) [][]string {
	var lines [][]string
	for scanner.Scan() {
		inputWithoutComments := strings.Split(scanner.Text(), ";")[0]
		var words []string
		ws := bufio.NewScanner(strings.NewReader(inputWithoutComments))
		ws.Split(bufio.ScanWords)
		for ws.Scan() {
			words = append(words, ws.Text())
		}
		lines = append(lines, words)
	}
	return lines
}

//line yacctab:1
var ZFPExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const ZFPPrivate = 57344

const ZFPLast = 223

var ZFPAct = [...]int{

	132, 3, 37, 38, 87, 133, 134, 135, 136, 137,
	138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
	148, 55, 57, 56, 58, 59, 60, 61, 62, 63,
	64, 65, 66, 67, 68, 69, 70, 16, 27, 112,
	100, 79, 167, 99, 76, 77, 116, 117, 11, 11,
	29, 98, 103, 101, 106, 107, 108, 109, 162, 73,
	97, 33, 151, 152, 153, 154, 155, 156, 157, 72,
	27, 94, 95, 55, 57, 56, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 163,
	128, 28, 104, 102, 125, 126, 127, 96, 74, 90,
	91, 75, 122, 86, 36, 25, 15, 171, 170, 169,
	78, 166, 129, 165, 161, 17, 18, 19, 11, 12,
	13, 14, 160, 159, 158, 164, 79, 149, 1, 130,
	34, 121, 168, 133, 134, 135, 136, 137, 138, 139,
	140, 141, 142, 143, 144, 145, 146, 147, 148, 55,
	57, 56, 58, 59, 60, 61, 62, 63, 64, 65,
	66, 67, 68, 69, 70, 120, 119, 114, 118, 113,
	111, 88, 93, 92, 85, 84, 83, 82, 81, 80,
	71, 35, 32, 31, 30, 23, 22, 21, 20, 105,
	124, 150, 115, 89, 26, 24, 131, 54, 53, 52,
	51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
	40, 41, 39, 7, 110, 123, 9, 5, 8, 4,
	2, 10, 6,
}
var ZFPPact = [...]int{

	-1000, -1000, 113, -1000, -1000, -1000, -1000, -10, -10, -10,
	-10, 184, 183, 182, 181, -1000, 45, -1000, -1000, -1000,
	46, 180, 179, 178, 13, -1000, 177, 78, 140, 176,
	55, 55, -1, -1000, -1000, -1000, 3, 64, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 175, 174, 173, 172, 171,
	170, 77, 167, 72, 169, 168, 167, 167, 71, 34,
	25, -2, -5, 49, 48, 16, -1000, 166, -1000, -1000,
	-6, -1000, -1000, -1000, -1000, -1000, 165, 163, -1000, 17,
	-1000, -1000, -1000, 164, 163, 163, 162, 161, 127, 140,
	-1000, -1000, -1000, -1000, -1000, 59, -1000, -1000, -1000, -1000,
	44, 125, 124, 123, -1000, 31, -1000, -1000, 120, 119,
	118, 110, 12, 43, 109, -1000, -1000, -1000, -1000, -1000,
	107, -4, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	105, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 104, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	103, -1000,
}
var ZFPPgo = [...]int{

	0, 222, 221, 220, 219, 218, 69, 217, 216, 215,
	214, 1, 213, 2, 3, 212, 211, 210, 209, 208,
	207, 206, 205, 204, 203, 202, 201, 200, 199, 198,
	197, 196, 0, 106, 195, 105, 194, 4, 193, 192,
	191, 190, 189, 128,
}
var ZFPR1 = [...]int{

	0, 43, 3, 3, 3, 3, 3, 1, 1, 2,
	10, 10, 4, 4, 5, 6, 6, 6, 6, 9,
	9, 7, 7, 8, 41, 41, 41, 42, 42, 42,
	42, 11, 11, 12, 12, 13, 13, 14, 14, 14,
	14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 15, 31, 31, 32, 32, 32, 32,
	32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
	32, 32, 17, 16, 19, 18, 20, 21, 22, 23,
	24, 25, 26, 27, 28, 29, 30, 38, 38, 39,
	39, 40, 40, 40, 40, 40, 40, 40, 37, 37,
	33, 34, 34, 35, 35, 36,
}
var ZFPR2 = [...]int{

	0, 1, 0, 2, 2, 2, 2, 1, 2, 6,
	0, 2, 1, 2, 7, 2, 2, 2, 2, 0,
	2, 1, 2, 7, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 5, 7, 1, 2, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 5, 1, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 2, 2, 2, 2, 4, 2, 5,
	2, 4, 2, 2, 4, 4, 6, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
	3, 1, 2, 1, 2, 6,
}
var ZFPChk = [...]int{

	-1000, -43, -3, -11, -4, -7, -1, -12, -5, -8,
	-2, 5, 6, 7, 8, -33, 47, -33, -33, -33,
	4, 4, 4, 4, -34, -35, -36, 25, 45, 4,
	4, 4, 4, 48, -35, 4, 26, -13, -14, -15,
	-17, -16, -18, -19, -20, -21, -22, -23, -24, -25,
	-26, -27, -28, -29, -30, 9, 11, 10, 12, 13,
	14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
	24, 4, -6, 4, 43, -6, 45, 42, 46, -14,
	4, 4, 4, 4, 4, 4, 26, -37, 4, -38,
	27, 28, 4, 4, -37, -37, 26, 26, 26, 45,
	45, 4, 44, 4, 44, -42, 38, 39, 40, 41,
	-10, 4, 45, 4, 4, -39, 29, 30, 4, 4,
	4, 4, -13, -9, -41, 35, 36, 37, 46, -11,
	4, -31, -32, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24, 4,
	-40, 31, 32, 33, 34, 35, 36, 37, 4, 4,
	4, 4, 46, 46, -11, 4, 4, 46, -32, 4,
	4, 4,
}
var ZFPDef = [...]int{

	2, -2, 1, 3, 4, 5, 6, 31, 12, 21,
	7, 0, 0, 0, 0, 32, 0, 13, 22, 8,
	0, 0, 0, 0, 0, 101, 103, 0, 0, 0,
	0, 0, 0, 100, 102, 104, 0, 0, 35, 37,
	38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
	48, 49, 50, 51, 52, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 10, 0, 33, 36,
	0, 72, 73, 75, 74, 76, 0, 78, 98, 0,
	87, 88, 80, 0, 82, 83, 0, 0, 0, 0,
	19, 15, 17, 16, 18, 0, 27, 28, 29, 30,
	0, 0, 0, 0, 99, 0, 89, 90, 0, 0,
	0, 0, 0, 0, 0, 24, 25, 26, 9, 11,
	0, 0, 54, 56, 57, 58, 59, 60, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 71, 77,
	0, 91, 92, 93, 94, 95, 96, 97, 81, 84,
	85, 0, 34, 14, 20, 23, 105, 53, 55, 79,
	0, 86,
}
var ZFPTok1 = [...]int{

	1,
}
var ZFPTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48,
}
var ZFPTok3 = [...]int{
	0,
}

var ZFPErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	ZFPDebug        = 0
	ZFPErrorVerbose = false
)

type ZFPLexer interface {
	Lex(lval *ZFPSymType) int
	Error(s string)
}

type ZFPParser interface {
	Parse(ZFPLexer) int
	Lookahead() int
    Result() []section.WithSigForward
}

type ZFPParserImpl struct {
	lval  ZFPSymType
	stack [ZFPInitialStackSize]ZFPSymType
	char  int
}

func (p *ZFPParserImpl) Lookahead() int {
	return p.char
}

func (p *ZFPParserImpl) Result() []section.WithSigForward {
    return output
}
func ZFPNewParser() ZFPParser {
	return &ZFPParserImpl{}
}

const ZFPFlag = -1000

func ZFPTokname(c int) string {
	if c >= 1 && c-1 < len(ZFPToknames) {
		if ZFPToknames[c-1] != "" {
			return ZFPToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func ZFPStatname(s int) string {
	if s >= 0 && s < len(ZFPStatenames) {
		if ZFPStatenames[s] != "" {
			return ZFPStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func ZFPErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !ZFPErrorVerbose {
		return "syntax error"
	}

	for _, e := range ZFPErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + ZFPTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := ZFPPact[state]
	for tok := TOKSTART; tok-1 < len(ZFPToknames); tok++ {
		if n := base + tok; n >= 0 && n < ZFPLast && ZFPChk[ZFPAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if ZFPDef[state] == -2 {
		i := 0
		for ZFPExca[i] != -1 || ZFPExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; ZFPExca[i] >= 0; i += 2 {
			tok := ZFPExca[i]
			if tok < TOKSTART || ZFPExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if ZFPExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += ZFPTokname(tok)
	}
	return res
}

func ZFPlex1(lex ZFPLexer, lval *ZFPSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = ZFPTok1[0]
		goto out
	}
	if char < len(ZFPTok1) {
		token = ZFPTok1[char]
		goto out
	}
	if char >= ZFPPrivate {
		if char < ZFPPrivate+len(ZFPTok2) {
			token = ZFPTok2[char-ZFPPrivate]
			goto out
		}
	}
	for i := 0; i < len(ZFPTok3); i += 2 {
		token = ZFPTok3[i+0]
		if token == char {
			token = ZFPTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = ZFPTok2[1] /* unknown char */
	}
	if ZFPDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", ZFPTokname(token), uint(char))
	}
	return char, token
}

func ZFPParse(ZFPlex ZFPLexer) int {
	return ZFPNewParser().Parse(ZFPlex)
}

func (ZFPrcvr *ZFPParserImpl) Parse(ZFPlex ZFPLexer) int {
	var ZFPn int
	var ZFPVAL ZFPSymType
	var ZFPDollar []ZFPSymType
	_ = ZFPDollar // silence set and not used
	ZFPS := ZFPrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	ZFPstate := 0
	ZFPrcvr.char = -1
	ZFPtoken := -1 // ZFPrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		ZFPstate = -1
		ZFPrcvr.char = -1
		ZFPtoken = -1
	}()
	ZFPp := -1
	goto ZFPstack

ret0:
	return 0

ret1:
	return 1

ZFPstack:
	/* put a state and value onto the stack */
	if ZFPDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", ZFPTokname(ZFPtoken), ZFPStatname(ZFPstate))
	}

	ZFPp++
	if ZFPp >= len(ZFPS) {
		nyys := make([]ZFPSymType, len(ZFPS)*2)
		copy(nyys, ZFPS)
		ZFPS = nyys
	}
	ZFPS[ZFPp] = ZFPVAL
	ZFPS[ZFPp].yys = ZFPstate

ZFPnewstate:
	ZFPn = ZFPPact[ZFPstate]
	if ZFPn <= ZFPFlag {
		goto ZFPdefault /* simple state */
	}
	if ZFPrcvr.char < 0 {
		ZFPrcvr.char, ZFPtoken = ZFPlex1(ZFPlex, &ZFPrcvr.lval)
	}
	ZFPn += ZFPtoken
	if ZFPn < 0 || ZFPn >= ZFPLast {
		goto ZFPdefault
	}
	ZFPn = ZFPAct[ZFPn]
	if ZFPChk[ZFPn] == ZFPtoken { /* valid shift */
		ZFPrcvr.char = -1
		ZFPtoken = -1
		ZFPVAL = ZFPrcvr.lval
		ZFPstate = ZFPn
		if Errflag > 0 {
			Errflag--
		}
		goto ZFPstack
	}

ZFPdefault:
	/* default state action */
	ZFPn = ZFPDef[ZFPstate]
	if ZFPn == -2 {
		if ZFPrcvr.char < 0 {
			ZFPrcvr.char, ZFPtoken = ZFPlex1(ZFPlex, &ZFPrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if ZFPExca[xi+0] == -1 && ZFPExca[xi+1] == ZFPstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			ZFPn = ZFPExca[xi+0]
			if ZFPn < 0 || ZFPn == ZFPtoken {
				break
			}
		}
		ZFPn = ZFPExca[xi+1]
		if ZFPn < 0 {
			goto ret0
		}
	}
	if ZFPn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			ZFPlex.Error(ZFPErrorMessage(ZFPstate, ZFPtoken))
			Nerrs++
			if ZFPDebug >= 1 {
				__yyfmt__.Printf("%s", ZFPStatname(ZFPstate))
				__yyfmt__.Printf(" saw %s\n", ZFPTokname(ZFPtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for ZFPp >= 0 {
				ZFPn = ZFPPact[ZFPS[ZFPp].yys] + ZFPErrCode
				if ZFPn >= 0 && ZFPn < ZFPLast {
					ZFPstate = ZFPAct[ZFPn] /* simulate a shift of "error" */
					if ZFPChk[ZFPstate] == ZFPErrCode {
						goto ZFPstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if ZFPDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", ZFPS[ZFPp].yys)
				}
				ZFPp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if ZFPDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", ZFPTokname(ZFPtoken))
			}
			if ZFPtoken == ZFPEofCode {
				goto ret1
			}
			ZFPrcvr.char = -1
			ZFPtoken = -1
			goto ZFPnewstate /* try again in the same state */
		}
	}

	/* reduction by production ZFPn */
	if ZFPDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", ZFPn, ZFPStatname(ZFPstate))
	}

	ZFPnt := ZFPn
	ZFPpt := ZFPp
	_ = ZFPpt // guard against "declared and not used"

	ZFPp -= ZFPR2[ZFPn]
	// ZFPp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if ZFPp+1 >= len(ZFPS) {
		nyys := make([]ZFPSymType, len(ZFPS)*2)
		copy(nyys, ZFPS)
		ZFPS = nyys
	}
	ZFPVAL = ZFPS[ZFPp+1]

	/* consult goto table to find next state */
	ZFPn = ZFPR1[ZFPn]
	ZFPg := ZFPPgo[ZFPn]
	ZFPj := ZFPg + ZFPS[ZFPp].yys + 1

	if ZFPj >= ZFPLast {
		ZFPstate = ZFPAct[ZFPg]
	} else {
		ZFPstate = ZFPAct[ZFPj]
		if ZFPChk[ZFPstate] != -ZFPn {
			ZFPstate = ZFPAct[ZFPg]
		}
	}
	// dummy call; replaced with literal code
	switch ZFPnt {

	case 1:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:202
		{
			output = ZFPDollar[1].sections
		}
	case 2:
		ZFPDollar = ZFPS[ZFPpt-0 : ZFPpt+1]
//line zonefileParser.y:207
		{
			ZFPVAL.sections = nil
		}
	case 3:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:211
		{
			ZFPVAL.sections = append(ZFPDollar[1].sections, ZFPDollar[2].assertion)
		}
	case 4:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:215
		{
			ZFPVAL.sections = append(ZFPDollar[1].sections, ZFPDollar[2].shard)
		}
	case 5:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:219
		{
			ZFPVAL.sections = append(ZFPDollar[1].sections, ZFPDollar[2].pshard)
		}
	case 6:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:223
		{
			ZFPVAL.sections = append(ZFPDollar[1].sections, ZFPDollar[2].zone)
		}
	case 8:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:229
		{
			AddSigs(ZFPDollar[1].zone, ZFPDollar[2].signatures)
			ZFPVAL.zone = ZFPDollar[1].zone
		}
	case 9:
		ZFPDollar = ZFPS[ZFPpt-6 : ZFPpt+1]
//line zonefileParser.y:235
		{
			ZFPVAL.zone = &section.Zone{
				SubjectZone: ZFPDollar[2].str,
				Context:     ZFPDollar[3].str,
				Content:     ZFPDollar[5].assertions,
			}
		}
	case 10:
		ZFPDollar = ZFPS[ZFPpt-0 : ZFPpt+1]
//line zonefileParser.y:244
		{
			ZFPVAL.assertions = nil
		}
	case 11:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:248
		{
			ZFPVAL.assertions = append(ZFPDollar[1].assertions, ZFPDollar[2].assertion)
		}
	case 13:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:254
		{
			AddSigs(ZFPDollar[1].shard, ZFPDollar[2].signatures)
			ZFPVAL.shard = ZFPDollar[1].shard
		}
	case 14:
		ZFPDollar = ZFPS[ZFPpt-7 : ZFPpt+1]
//line zonefileParser.y:260
		{
			ZFPVAL.shard = &section.Shard{
				SubjectZone: ZFPDollar[2].str,
				Context:     ZFPDollar[3].str,
				RangeFrom:   ZFPDollar[4].shardRange[0],
				RangeTo:     ZFPDollar[4].shardRange[1],
				Content:     ZFPDollar[6].assertions,
			}
		}
	case 15:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:271
		{
			ZFPVAL.shardRange = []string{ZFPDollar[1].str, ZFPDollar[2].str}
		}
	case 16:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:275
		{
			ZFPVAL.shardRange = []string{"<", ZFPDollar[2].str}
		}
	case 17:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:279
		{
			ZFPVAL.shardRange = []string{ZFPDollar[1].str, ">"}
		}
	case 18:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:283
		{
			ZFPVAL.shardRange = []string{"<", ">"}
		}
	case 19:
		ZFPDollar = ZFPS[ZFPpt-0 : ZFPpt+1]
//line zonefileParser.y:288
		{
			ZFPVAL.assertions = nil
		}
	case 20:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:292
		{
			ZFPVAL.assertions = append(ZFPDollar[1].assertions, ZFPDollar[2].assertion)
		}
	case 22:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:298
		{
			AddSigs(ZFPDollar[1].pshard, ZFPDollar[2].signatures)
			ZFPVAL.pshard = ZFPDollar[1].pshard
		}
	case 23:
		ZFPDollar = ZFPS[ZFPpt-7 : ZFPpt+1]
//line zonefileParser.y:304
		{
			decodedFilter, err := hex.DecodeString(ZFPDollar[7].str)
			if err != nil {
				log.Error("semantic error:", "Was not able to decode Bloom filter", err)
			}
			ZFPVAL.pshard = &section.Pshard{
				SubjectZone: ZFPDollar[2].str,
				Context:     ZFPDollar[3].str,
				RangeFrom:   ZFPDollar[4].shardRange[0],
				RangeTo:     ZFPDollar[4].shardRange[1],
				BloomFilter: section.BloomFilter{
					Algorithm: ZFPDollar[5].bfAlgo,
					Hash:      ZFPDollar[6].hashType,
					Filter:    bitarray.BitArray(decodedFilter),
				},
			}
		}
	case 24:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:323
		{
			ZFPVAL.hashType = algorithmTypes.Shake256
		}
	case 25:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:327
		{
			ZFPVAL.hashType = algorithmTypes.Fnv64
		}
	case 26:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:331
		{
			ZFPVAL.hashType = algorithmTypes.Fnv128
		}
	case 27:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:336
		{
			ZFPVAL.bfAlgo = section.BloomKM12
		}
	case 28:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:340
		{
			ZFPVAL.bfAlgo = section.BloomKM16
		}
	case 29:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:344
		{
			ZFPVAL.bfAlgo = section.BloomKM20
		}
	case 30:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:348
		{
			ZFPVAL.bfAlgo = section.BloomKM24
		}
	case 32:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:354
		{
			AddSigs(ZFPDollar[1].assertion, ZFPDollar[2].signatures)
			ZFPVAL.assertion = ZFPDollar[1].assertion
		}
	case 33:
		ZFPDollar = ZFPS[ZFPpt-5 : ZFPpt+1]
//line zonefileParser.y:360
		{
			ZFPVAL.assertion = &section.Assertion{
				SubjectName: ZFPDollar[2].str,
				Content:     ZFPDollar[4].objects,
			}
		}
	case 34:
		ZFPDollar = ZFPS[ZFPpt-7 : ZFPpt+1]
//line zonefileParser.y:367
		{
			ZFPVAL.assertion = &section.Assertion{
				SubjectName: ZFPDollar[2].str,
				SubjectZone: ZFPDollar[3].str,
				Context:     ZFPDollar[4].str,
				Content:     ZFPDollar[6].objects,
			}
		}
	case 35:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:377
		{
			ZFPVAL.objects = []object.Object{ZFPDollar[1].object}
		}
	case 36:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:381
		{
			ZFPVAL.objects = append(ZFPDollar[1].objects, ZFPDollar[2].object)
		}
	case 53:
		ZFPDollar = ZFPS[ZFPpt-5 : ZFPpt+1]
//line zonefileParser.y:403
		{
			ZFPVAL.object = object.Object{
				Type: object.OTName,
				Value: object.Name{
					Name:  ZFPDollar[2].str,
					Types: ZFPDollar[4].objectTypes,
				},
			}
		}
	case 54:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:414
		{
			ZFPVAL.objectTypes = []object.Type{ZFPDollar[1].objectType}
		}
	case 55:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:418
		{
			ZFPVAL.objectTypes = append(ZFPDollar[1].objectTypes, ZFPDollar[2].objectType)
		}
	case 56:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:423
		{
			ZFPVAL.objectType = object.OTName
		}
	case 57:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:427
		{
			ZFPVAL.objectType = object.OTIP4Addr
		}
	case 58:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:431
		{
			ZFPVAL.objectType = object.OTIP6Addr
		}
	case 59:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:435
		{
			ZFPVAL.objectType = object.OTScionAddr4
		}
	case 60:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:439
		{
			ZFPVAL.objectType = object.OTScionAddr6
		}
	case 61:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:443
		{
			ZFPVAL.objectType = object.OTRedirection
		}
	case 62:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:447
		{
			ZFPVAL.objectType = object.OTDelegation
		}
	case 63:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:451
		{
			ZFPVAL.objectType = object.OTNameset
		}
	case 64:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:455
		{
			ZFPVAL.objectType = object.OTCertInfo
		}
	case 65:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:459
		{
			ZFPVAL.objectType = object.OTCTInfo
		}
	case 66:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:463
		{
			ZFPVAL.objectType = object.OTServiceInfo
		}
	case 67:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:467
		{
			ZFPVAL.objectType = object.OTRegistrar
		}
	case 68:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:471
		{
			ZFPVAL.objectType = object.OTRegistrant
		}
	case 69:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:475
		{
			ZFPVAL.objectType = object.OTInfraKey
		}
	case 70:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:479
		{
			ZFPVAL.objectType = object.OTExtraKey
		}
	case 71:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:483
		{
			ZFPVAL.objectType = object.OTNextKey
		}
	case 72:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:487
		{
			ip := net.ParseIP(ZFPDollar[2].str)
			if ip == nil {
				log.Error("semantic error:", "ParseIP", "not a valid IP")
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTIP6Addr,
				Value: ip,
			}
		}
	case 73:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:498
		{
			ip := net.ParseIP(ZFPDollar[2].str)
			if ip == nil {
				log.Error("semantic error:", "ParseIP", "not a valid IP")
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTIP4Addr,
				Value: ip,
			}
		}
	case 74:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:509
		{
			addr, err := snet.AddrFromString(ZFPDollar[2].str)
			if err != nil {
				log.Error("semantic error:", "AddrFromString", "not a valid SCION address")
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTScionAddr6,
				Value: &object.SCIONAddress{addr.IA, addr.Host.L3},
			}
		}
	case 75:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:520
		{
			addr, err := snet.AddrFromString(ZFPDollar[2].str)
			if err != nil {
				log.Error("semantic error:", "AddrFromString", "not a valid SCION address")
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTScionAddr4,
				Value: &object.SCIONAddress{addr.IA, addr.Host.L3},
			}
		}
	case 76:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:531
		{
			ZFPVAL.object = object.Object{
				Type:  object.OTRedirection,
				Value: ZFPDollar[2].str,
			}
		}
	case 77:
		ZFPDollar = ZFPS[ZFPpt-4 : ZFPpt+1]
//line zonefileParser.y:539
		{
			pkey, err := DecodeEd25519PublicKeyData(ZFPDollar[4].str, ZFPDollar[3].str)
			if err != nil {
				log.Error("semantic error:", "DecodeEd25519PublicKeyData", err)
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTDelegation,
				Value: pkey,
			}
		}
	case 78:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:551
		{
			ZFPVAL.object = object.Object{
				Type:  object.OTNameset,
				Value: ZFPDollar[2].str,
			}
		}
	case 79:
		ZFPDollar = ZFPS[ZFPpt-5 : ZFPpt+1]
//line zonefileParser.y:559
		{
			cert, err := DecodeCertificate(ZFPDollar[2].protocolType, ZFPDollar[3].certUsage, ZFPDollar[4].hashType, ZFPDollar[5].str)
			if err != nil {
				log.Error("semantic error:", "Decode certificate", err)
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTCertInfo,
				Value: cert,
			}
		}
	case 80:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:571
		{
			ct, err := DecodeCT(ZFPDollar[2].str)
			if err != nil {
				log.Error("semantic error:", "Decode certificate transparency proof", err)
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTCTInfo,
				Value: ct,
			}
		}
	case 81:
		ZFPDollar = ZFPS[ZFPpt-4 : ZFPpt+1]
//line zonefileParser.y:583
		{
			srv, err := DecodeSrv(ZFPDollar[2].str, ZFPDollar[3].str, ZFPDollar[4].str)
			if err != nil {
				log.Error("semantic error:", "error", err)
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTServiceInfo,
				Value: srv,
			}
		}
	case 82:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:595
		{
			ZFPVAL.object = object.Object{
				Type:  object.OTRegistrar,
				Value: ZFPDollar[2].str,
			}
		}
	case 83:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:603
		{
			ZFPVAL.object = object.Object{
				Type:  object.OTRegistrant,
				Value: ZFPDollar[2].str,
			}
		}
	case 84:
		ZFPDollar = ZFPS[ZFPpt-4 : ZFPpt+1]
//line zonefileParser.y:611
		{
			pkey, err := DecodeEd25519PublicKeyData(ZFPDollar[4].str, ZFPDollar[3].str)
			if err != nil {
				log.Error("semantic error:", "DecodeEd25519PublicKeyData", err)
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTInfraKey,
				Value: pkey,
			}
		}
	case 85:
		ZFPDollar = ZFPS[ZFPpt-4 : ZFPpt+1]
//line zonefileParser.y:623
		{ //TODO CFE as of now there is only the rains key space. There will
			//be additional rules in case there are new key spaces
			pkey, err := DecodeEd25519PublicKeyData(ZFPDollar[4].str, ZFPDollar[3].str)
			if err != nil {
				log.Error("semantic error:", "DecodeEd25519PublicKeyData", err)
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTExtraKey,
				Value: pkey,
			}
		}
	case 86:
		ZFPDollar = ZFPS[ZFPpt-6 : ZFPpt+1]
//line zonefileParser.y:636
		{
			pkey, err := DecodeEd25519PublicKeyData(ZFPDollar[4].str, ZFPDollar[3].str)
			if err != nil {
				log.Error("semantic error:", "DecodeEd25519PublicKeyData", err)
			}
			pkey.ValidSince, pkey.ValidUntil, err = DecodeValidity(ZFPDollar[5].str, ZFPDollar[6].str)
			if err != nil {
				log.Error("semantic error:", "error", err)
			}
			ZFPVAL.object = object.Object{
				Type:  object.OTNextKey,
				Value: pkey,
			}
		}
	case 87:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:652
		{
			ZFPVAL.protocolType = object.PTUnspecified
		}
	case 88:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:656
		{
			ZFPVAL.protocolType = object.PTTLS
		}
	case 89:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:661
		{
			ZFPVAL.certUsage = object.CUTrustAnchor
		}
	case 90:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:665
		{
			ZFPVAL.certUsage = object.CUEndEntity
		}
	case 91:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:670
		{
			ZFPVAL.hashType = algorithmTypes.NoHashAlgo
		}
	case 92:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:674
		{
			ZFPVAL.hashType = algorithmTypes.Sha256
		}
	case 93:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:678
		{
			ZFPVAL.hashType = algorithmTypes.Sha384
		}
	case 94:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:682
		{
			ZFPVAL.hashType = algorithmTypes.Sha512
		}
	case 95:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:686
		{
			ZFPVAL.hashType = algorithmTypes.Shake256
		}
	case 96:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:690
		{
			ZFPVAL.hashType = algorithmTypes.Fnv64
		}
	case 97:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:694
		{
			ZFPVAL.hashType = algorithmTypes.Fnv128
		}
	case 99:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:700
		{
			ZFPVAL.str = ZFPDollar[1].str + " " + ZFPDollar[2].str
		}
	case 100:
		ZFPDollar = ZFPS[ZFPpt-3 : ZFPpt+1]
//line zonefileParser.y:705
		{
			ZFPVAL.signatures = ZFPDollar[2].signatures
		}
	case 101:
		ZFPDollar = ZFPS[ZFPpt-1 : ZFPpt+1]
//line zonefileParser.y:710
		{
			ZFPVAL.signatures = []signature.Sig{ZFPDollar[1].signature}
		}
	case 102:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:714
		{
			ZFPVAL.signatures = append(ZFPDollar[1].signatures, ZFPDollar[2].signature)
		}
	case 104:
		ZFPDollar = ZFPS[ZFPpt-2 : ZFPpt+1]
//line zonefileParser.y:720
		{
			sigData, err := hex.DecodeString(ZFPDollar[2].str)
			if err != nil {
				log.Error("semantic error:", "DecodeEd25519SignatureData", err)
			}
			ZFPDollar[1].signature.Data = sigData
			ZFPVAL.signature = ZFPDollar[1].signature
		}
	case 105:
		ZFPDollar = ZFPS[ZFPpt-6 : ZFPpt+1]
//line zonefileParser.y:730
		{
			publicKeyID, err := DecodePublicKeyID(ZFPDollar[4].str)
			if err != nil {
				log.Error("semantic error:", "DecodePublicKeyID", err)
			}
			validSince, validUntil, err := DecodeValidity(ZFPDollar[5].str, ZFPDollar[6].str)
			if err != nil {
				log.Error("semantic error:", "DecodeValidity", err)
			}
			ZFPVAL.signature = signature.Sig{
				PublicKeyID: publicKeyID,
				ValidSince:  validSince,
				ValidUntil:  validUntil,
			}
		}
	}
	goto ZFPstack /* stack new state and value */
}
